<a href="https://colab.research.google.com/github/eTcilopp/temp_python_intro_course_gb/blob/master/files/Homework10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

| Задание 44 |
| --- |
| В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

In [20]:
import pandas as pd
import random

lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})
data.head()

  whoAmI
0  human
1  human
2  human
3  robot
4  robot

In [22]:
data.loc[data['whoAmI']=='robot', 'robot_Onehot'] = 1
data.loc[data['whoAmI']=='human', 'human_Onehot'] = 1
data['robot_Onehot'] = data['robot_Onehot'].fillna(0)
data['human_Onehot'] = data['human_Onehot'].fillna(0)
data = data.astype({'robot_Onehot':'int', 'human_Onehot':'int'})
data.head()

  whoAmI  robot_Onehot  human_Onehot
0  human             0             1
1  human             0             1
2  human             0             1
3  robot             1             0
4  robot             1             0